OPENAI_API_KEY: "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"
PINECONE_API_KEY: "pcsk_5kvz8B_HAmitPhECurHyfBSUgibyaD7vs4vaoFobAv2fC6TmBYpiN3L4NQG5rEkNhegtUc"
GOOGLE_API_KEI: ""